/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f8f9fb',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb780',
        'primary-fixed': '#d2e4ff',
        'outline-variant': '#c2c7d1',
        primary: '#00355f',
        'secondary-fixed-dim': '#4fdbc8',
        'surface-variant': '#e1e2e4',
        'primary-container': '#0f4c81',
        'secondary-container': '#6df5e1',
        'surface-container-highest': '#e1e2e4',
        'on-error': '#ffffff',
        'surface-dim': '#d9dadc',
        'surface-container-low': '#f2f4f6',
        'tertiary-fixed': '#ffdcc4',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#a0c9ff',
        'on-secondary-fixed-variant': '#005048',
        'on-background': '#191c1e',
        'surface-container-high': '#e7e8ea',
        'on-primary-container': '#8ebdf9',
        'on-surface-variant': '#42474f',
        'inverse-primary': '#a0c9ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001c37',
        'tertiary-container': '#743b00',
        'inverse-surface': '#2e3132',
        'on-tertiary-fixed-variant': '#6f3800',
        'surface-container': '#edeef0',
        error: '#ba1a1a',
        tertiary: '#532800',
        'on-secondary-container': '#006f64',
        'on-tertiary-container': '#f9a767',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#07497d',
        'on-error-container': '#93000a',
        'secondary-fixed': '#71f8e4',
        outline: '#727780',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f0f1f3',
        'surface-tint': '#2d6197',
        'on-surface': '#191c1e',
        secondary: '#006b5f',
        'on-secondary-fixed': '#00201c',
        surface: '#f8f9fb',
        'on-tertiary-fixed': '#2f1400',
        'surface-bright': '#f8f9fb',
        'brand-blue': '#3F3091',
        'brand-orange': '#F07E22',
        'brand-ink': '#184B78',
        'brand-green': '#00796B',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0 24px 40px -12px rgba(25, 28, 30, 0.08)',
        'ambient-sm': '0 8px 24px -8px rgba(25, 28, 30, 0.06)',
        'ambient-xl': '0 40px 80px -24px rgba(0, 53, 95, 0.22)',
        glow: '0 0 80px -8px rgba(15, 76, 129, 0.45)',
      },
      maxWidth: {
        container: '1200px',
      },
      dropShadow: {
        hero: '0 24px 48px rgba(0, 53, 95, 0.25)',
      },
      keyframes: {
        appear: {
          '0%': { opacity: '0', transform: 'translateY(14px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'appear-zoom': {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.45', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(1.05)' },
        },
        'float-y': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        appear: 'appear 0.9s cubic-bezier(0.16, 1, 0.3, 1) both',
        'appear-zoom': 'appear-zoom 1.1s cubic-bezier(0.16, 1, 0.3, 1) both',
        'glow-pulse': 'glow-pulse 6s ease-in-out infinite',
        'float-y': 'float-y 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}


